/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "test/master/test_master.check" instead.
 */

#include <check.h>

#line 1 "test/master/test_master.check"

START_TEST(calc_entered_test)
{
#line 3
ck_assert_msg(calc_entered("calc") == 1, "calc\n");
ck_assert_msg(calc_entered("calc\n") == 1, "calc\n");
ck_assert_msg(calc_entered("calc\0") == 1, "calc\n");
ck_assert_msg(calc_entered("calc\n123") == 1, "calc\n");
ck_assert_msg(calc_entered("CALC") == 0, "calc\n");
ck_assert_msg(calc_entered("asdjsd") == 0, "calc\n");

}
END_TEST

START_TEST(valid_input_test)
{
#line 11
ck_assert(valid_input("2+2") == 1);
ck_assert(valid_input("2-3") == 1);
ck_assert(valid_input("2*276") == 1);
ck_assert(valid_input("234/3") == 1);
ck_assert(valid_input("2:3") == 1);
ck_assert(valid_input(" 3 +   834 ") == 1);
ck_assert(valid_input("-3-43") == 1);
ck_assert(valid_input("2//3") == 0);
ck_assert(valid_input("2343") == 0);
ck_assert(valid_input("a-2") == 0);
ck_assert(valid_input("4-2=") == 0);
ck_assert(valid_input("") == 0);
ck_assert(valid_input("=") == 0);
ck_assert(valid_input("+3") == 0);
ck_assert(valid_input("3 34 + 43") == 0);


}
END_TEST

START_TEST(save_input_test)
{
#line 29
#include "src/master/master.c"
struct inputs_t inputs;
inputs.n_elem = 0;
inputs.n_alloc = 0;
char *str = strdup("eminem");
save_input(&inputs, str);
ck_assert(inputs.n_elem == 1);
ck_assert(strcmp(inputs.data[0], str) == 0);
mqd_t mq = create_mqueue();
add_to_queue(&inputs, mq);
str = strdup("eminem");
save_input(&inputs, str);
ck_assert(inputs.n_elem == 1);
ck_assert(strcmp(inputs.data[0], str) == 0);
}
END_TEST

int main(void)
{
    Suite *s1 = suite_create("Core");
    TCase *tc1_1 = tcase_create("Core");
    SRunner *sr = srunner_create(s1);
    int nf;

    suite_add_tcase(s1, tc1_1);
    tcase_add_test(tc1_1, calc_entered_test);
    tcase_add_test(tc1_1, valid_input_test);
    tcase_add_test(tc1_1, save_input_test);

    srunner_run_all(sr, CK_ENV);
    nf = srunner_ntests_failed(sr);
    srunner_free(sr);

    return nf == 0 ? 0 : 1;
}
